### ISSUE TITLE
File Not Found error

### ISSUE THREAD

**Issue by nikk916** [IAmSuyogJadhav/Brainy#12]
Hey, I am getting file not found error while executing flask run.
 FileNotFoundError: [WinError 3] The system cannot find the path specified: './app/static/images'
May I please know how to fix this error?
![Screenshot (5)](https://user-images.githubusercontent.com/60432433/73358811-7492f500-42c5-11ea-9cff-effe65080e1b.png)

**Comment by IAmSuyogJadhav** [comment]
Creating an empty folder inside `app/static` named `images` should fix it.
