### ISSUE TITLE
Internal Server Error 

### ISSUE THREAD

**Issue by csrvictory** [IAmSuyogJadhav/Brainy#14]
after creating mmri file, for analyzing it, 
i am getting the following error
could you plz help on it

Internal Server Error 
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by ajinkyajawale14** [comment]
Hi, the error must be at localhost/analyze. I am getting this same error. I checked in terminal its showing placeholder not found in right TensorFlow version. it requires the tf version when the project was built. did you resolved this error? can you help with it? @csrvictory

**Comment by csrvictory** [comment]
I cleared this error
by creating a sub folder named gifs in side static folder

**Comment by ajinkyajawale14** [comment]
Yes it works now thank you
