### ISSUE TITLE
Model not running on all systems

### ISSUE THREAD

**Issue by IAmSuyogJadhav** [IAmSuyogJadhav/Brainy#2]
There's some problem with the tensorflow version used to train the model. It throws an error on some of the systems.

**Comment by Akasireddy99** [comment]
Can you mention which version of TensorFlow was working on your local machine?

**Comment by IAmSuyogJadhav** [comment]
The model wasn't trained on my PC. It was working well on Udbhav's. @ubamba98 , What was the version of tensorflow on your system back then?

**Comment by IAmSuyogJadhav** [comment]
Solved by the recent PR, closing
