### ISSUE TITLE
file not found - Using ANTs package on Google Colaboratory

### ISSUE THREAD

**Issue by Noura-CS** [IAmSuyogJadhav/Brainy#31]
Hello 

I hope you are fine

I have tried your way for installing ANTs on google Colaboratory, and it worked at first. But now, the file doesn't exist anymore. Can you help me with this issue please..

Thank you in advanced

**Comment by IAmSuyogJadhav** [comment]
Hi,
My drive had to be cleared recently as I left my last institute. I will try to re-build it using the notebook and see if I can get a working binary. I will post on the website if I succeed and update you here!

**Comment by Noura-CS** [comment]
Thank you for the response. I tried the code written here (http://miykael.github.io/nipype-beginner-s-guide/installation.html#ants). Whatsoever, I could not do this step (Change the CMAKE_INSTALL_PREFIX value to /usr/local/antsbin)..

Thank you

**Comment by Noura-CS** [comment]
[Build_ANTS_Binaries_[fromSourceCode].pdf](https://github.com/IAmSuyogJadhav/Brainy/files/10893303/Build_ANTS_Binaries_.fromSourceCode.pdf)

I have tried this, and it worked pretty well.
Thank You

**Comment by IAmSuyogJadhav** [comment]
Oh, great!

**Comment by IAmSuyogJadhav** [comment]
Just for anyone else looking for the binary: Good news!, I found the file in one of my backups. I have updated the link on the website, it should be live in a short while.
