### ISSUE TITLE
Where to get the .mha or .nii.gz files can you provide some samples

### ISSUE THREAD

**Issue by LalithMovva** [IAmSuyogJadhav/Brainy#8]

**Comment by IAmSuyogJadhav** [comment]
Not a problem. I will upload 2-3 samples from BraTS 2018 dataset shortly. The segmentations might be blurrier due to the low output resolution, but you can download the segmentations from the app and use a program like ITKSnap to view them clearly.

**Comment by LalithMovva** [comment]
Thank you very much.

**Comment by LalithMovva** [comment]
You said that you will upload and i can download from the  app . Do you
mean in the github or any other source?

**Comment by IAmSuyogJadhav** [comment]
The app runs locally. The files you "upload" to it will just be stored in a separate folder. The "Download" option essentially makes a request and exports the results of the model to a local folder and then copies it from there to your downloads directory. No internet is involved. It is all happening on your PC.
Just launch the app. I have added some helpful instructions on the main page.

**Comment by LalithMovva** [comment]
Thanks alot for the information.

**Comment by IAmSuyogJadhav** [comment]
Closing this issue since the original request has been satisfied. Feel free to raise a new issue, if needed be.
